version: '3.8'

services:
  db:
    image: postgres:15
    container_name: job_tracker_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Platypus1234$
      POSTGRES_DB: jobtracker
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: